// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include "native_query.g.h"

struct _SqlqMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(SqlqMessageCodec, sqlq_message_codec, fl_standard_message_codec_get_type())

/** Purpose: Encode one generated channel value. @param codec is the active codec. @param buffer receives bytes. @param value is encoded. @param error receives failure. @returns TRUE on success. @throws Nothing. */
static gboolean sqlq_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(sqlq_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

/** Purpose: Decode one generated channel value. @param codec is the active codec. @param buffer supplies bytes. @param offset advances after decoding. @param type selects the value codec. @param error receives failure. @returns A newly owned value or null. @throws Nothing. */
static FlValue* sqlq_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(sqlq_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

/** Purpose: Initialize generated MessageCodec state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_message_codec_init(SqlqMessageCodec* self) {
}

/** Purpose: Bind generated MessageCodec lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_message_codec_class_init(SqlqMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = sqlq_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = sqlq_message_codec_read_value_of_type;
}

/** Purpose: Create the generated channel codec. @returns A newly owned codec. @throws Nothing. */
static SqlqMessageCodec* sqlq_message_codec_new() {
  SqlqMessageCodec* self = SQLQ_MESSAGE_CODEC(g_object_new(sqlq_message_codec_get_type(), nullptr));
  return self;
}

struct _SqlqNativeQueryHostApiGetCapabilitiesResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiGetCapabilitiesResponse, sqlq_native_query_host_api_get_capabilities_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiGetCapabilitiesResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_get_capabilities_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiGetCapabilitiesResponse* self = SQLQ_NATIVE_QUERY_HOST_API_GET_CAPABILITIES_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_get_capabilities_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiGetCapabilitiesResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_get_capabilities_response_init(SqlqNativeQueryHostApiGetCapabilitiesResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiGetCapabilitiesResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_get_capabilities_response_class_init(SqlqNativeQueryHostApiGetCapabilitiesResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_get_capabilities_response_dispose;
}

SqlqNativeQueryHostApiGetCapabilitiesResponse* sqlq_native_query_host_api_get_capabilities_response_new(FlValue* return_value) {
  SqlqNativeQueryHostApiGetCapabilitiesResponse* self = SQLQ_NATIVE_QUERY_HOST_API_GET_CAPABILITIES_RESPONSE(g_object_new(sqlq_native_query_host_api_get_capabilities_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

SqlqNativeQueryHostApiGetCapabilitiesResponse* sqlq_native_query_host_api_get_capabilities_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiGetCapabilitiesResponse* self = SQLQ_NATIVE_QUERY_HOST_API_GET_CAPABILITIES_RESPONSE(g_object_new(sqlq_native_query_host_api_get_capabilities_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiQueryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiQueryResponse, sqlq_native_query_host_api_query_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiQueryResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_query_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiQueryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_QUERY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_query_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiQueryResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_query_response_init(SqlqNativeQueryHostApiQueryResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiQueryResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_query_response_class_init(SqlqNativeQueryHostApiQueryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_query_response_dispose;
}

SqlqNativeQueryHostApiQueryResponse* sqlq_native_query_host_api_query_response_new(FlValue* return_value) {
  SqlqNativeQueryHostApiQueryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_QUERY_RESPONSE(g_object_new(sqlq_native_query_host_api_query_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

SqlqNativeQueryHostApiQueryResponse* sqlq_native_query_host_api_query_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiQueryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_QUERY_RESPONSE(g_object_new(sqlq_native_query_host_api_query_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiMutateResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiMutateResponse, sqlq_native_query_host_api_mutate_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiMutateResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_mutate_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiMutateResponse* self = SQLQ_NATIVE_QUERY_HOST_API_MUTATE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_mutate_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiMutateResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_mutate_response_init(SqlqNativeQueryHostApiMutateResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiMutateResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_mutate_response_class_init(SqlqNativeQueryHostApiMutateResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_mutate_response_dispose;
}

SqlqNativeQueryHostApiMutateResponse* sqlq_native_query_host_api_mutate_response_new(FlValue* return_value) {
  SqlqNativeQueryHostApiMutateResponse* self = SQLQ_NATIVE_QUERY_HOST_API_MUTATE_RESPONSE(g_object_new(sqlq_native_query_host_api_mutate_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

SqlqNativeQueryHostApiMutateResponse* sqlq_native_query_host_api_mutate_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiMutateResponse* self = SQLQ_NATIVE_QUERY_HOST_API_MUTATE_RESPONSE(g_object_new(sqlq_native_query_host_api_mutate_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiBatchResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiBatchResponse, sqlq_native_query_host_api_batch_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiBatchResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_batch_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiBatchResponse* self = SQLQ_NATIVE_QUERY_HOST_API_BATCH_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_batch_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiBatchResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_batch_response_init(SqlqNativeQueryHostApiBatchResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiBatchResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_batch_response_class_init(SqlqNativeQueryHostApiBatchResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_batch_response_dispose;
}

SqlqNativeQueryHostApiBatchResponse* sqlq_native_query_host_api_batch_response_new(FlValue* return_value) {
  SqlqNativeQueryHostApiBatchResponse* self = SQLQ_NATIVE_QUERY_HOST_API_BATCH_RESPONSE(g_object_new(sqlq_native_query_host_api_batch_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

SqlqNativeQueryHostApiBatchResponse* sqlq_native_query_host_api_batch_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiBatchResponse* self = SQLQ_NATIVE_QUERY_HOST_API_BATCH_RESPONSE(g_object_new(sqlq_native_query_host_api_batch_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiObserveStartResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiObserveStartResponse, sqlq_native_query_host_api_observe_start_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiObserveStartResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_start_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiObserveStartResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OBSERVE_START_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_observe_start_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiObserveStartResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_start_response_init(SqlqNativeQueryHostApiObserveStartResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiObserveStartResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_start_response_class_init(SqlqNativeQueryHostApiObserveStartResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_observe_start_response_dispose;
}

SqlqNativeQueryHostApiObserveStartResponse* sqlq_native_query_host_api_observe_start_response_new(const gchar* return_value) {
  SqlqNativeQueryHostApiObserveStartResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OBSERVE_START_RESPONSE(g_object_new(sqlq_native_query_host_api_observe_start_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(return_value));
  return self;
}

SqlqNativeQueryHostApiObserveStartResponse* sqlq_native_query_host_api_observe_start_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiObserveStartResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OBSERVE_START_RESPONSE(g_object_new(sqlq_native_query_host_api_observe_start_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiObserveStopResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiObserveStopResponse, sqlq_native_query_host_api_observe_stop_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiObserveStopResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_stop_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiObserveStopResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OBSERVE_STOP_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_observe_stop_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiObserveStopResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_stop_response_init(SqlqNativeQueryHostApiObserveStopResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiObserveStopResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_stop_response_class_init(SqlqNativeQueryHostApiObserveStopResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_observe_stop_response_dispose;
}

SqlqNativeQueryHostApiObserveStopResponse* sqlq_native_query_host_api_observe_stop_response_new() {
  SqlqNativeQueryHostApiObserveStopResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OBSERVE_STOP_RESPONSE(g_object_new(sqlq_native_query_host_api_observe_stop_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

SqlqNativeQueryHostApiObserveStopResponse* sqlq_native_query_host_api_observe_stop_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiObserveStopResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OBSERVE_STOP_RESPONSE(g_object_new(sqlq_native_query_host_api_observe_stop_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiOpenBinaryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiOpenBinaryResponse, sqlq_native_query_host_api_open_binary_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiOpenBinaryResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_open_binary_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiOpenBinaryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OPEN_BINARY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_open_binary_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiOpenBinaryResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_open_binary_response_init(SqlqNativeQueryHostApiOpenBinaryResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiOpenBinaryResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_open_binary_response_class_init(SqlqNativeQueryHostApiOpenBinaryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_open_binary_response_dispose;
}

SqlqNativeQueryHostApiOpenBinaryResponse* sqlq_native_query_host_api_open_binary_response_new(FlValue* return_value) {
  SqlqNativeQueryHostApiOpenBinaryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OPEN_BINARY_RESPONSE(g_object_new(sqlq_native_query_host_api_open_binary_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

SqlqNativeQueryHostApiOpenBinaryResponse* sqlq_native_query_host_api_open_binary_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiOpenBinaryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_OPEN_BINARY_RESPONSE(g_object_new(sqlq_native_query_host_api_open_binary_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiCloseBinaryResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiCloseBinaryResponse, sqlq_native_query_host_api_close_binary_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiCloseBinaryResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_close_binary_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiCloseBinaryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_CLOSE_BINARY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_close_binary_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiCloseBinaryResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_close_binary_response_init(SqlqNativeQueryHostApiCloseBinaryResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiCloseBinaryResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_close_binary_response_class_init(SqlqNativeQueryHostApiCloseBinaryResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_close_binary_response_dispose;
}

SqlqNativeQueryHostApiCloseBinaryResponse* sqlq_native_query_host_api_close_binary_response_new() {
  SqlqNativeQueryHostApiCloseBinaryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_CLOSE_BINARY_RESPONSE(g_object_new(sqlq_native_query_host_api_close_binary_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_null());
  return self;
}

SqlqNativeQueryHostApiCloseBinaryResponse* sqlq_native_query_host_api_close_binary_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiCloseBinaryResponse* self = SQLQ_NATIVE_QUERY_HOST_API_CLOSE_BINARY_RESPONSE(g_object_new(sqlq_native_query_host_api_close_binary_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApiCallExtensionResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApiCallExtensionResponse, sqlq_native_query_host_api_call_extension_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApiCallExtensionResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_call_extension_response_dispose(GObject* object) {
  SqlqNativeQueryHostApiCallExtensionResponse* self = SQLQ_NATIVE_QUERY_HOST_API_CALL_EXTENSION_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_host_api_call_extension_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApiCallExtensionResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_call_extension_response_init(SqlqNativeQueryHostApiCallExtensionResponse* self) {
}

/** Purpose: Bind generated NativeQueryHostApiCallExtensionResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_call_extension_response_class_init(SqlqNativeQueryHostApiCallExtensionResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_call_extension_response_dispose;
}

SqlqNativeQueryHostApiCallExtensionResponse* sqlq_native_query_host_api_call_extension_response_new(FlValue* return_value) {
  SqlqNativeQueryHostApiCallExtensionResponse* self = SQLQ_NATIVE_QUERY_HOST_API_CALL_EXTENSION_RESPONSE(g_object_new(sqlq_native_query_host_api_call_extension_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, return_value != nullptr ? fl_value_ref(return_value) : fl_value_new_null());
  return self;
}

SqlqNativeQueryHostApiCallExtensionResponse* sqlq_native_query_host_api_call_extension_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  SqlqNativeQueryHostApiCallExtensionResponse* self = SQLQ_NATIVE_QUERY_HOST_API_CALL_EXTENSION_RESPONSE(g_object_new(sqlq_native_query_host_api_call_extension_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _SqlqNativeQueryHostApi {
  GObject parent_instance;

  const SqlqNativeQueryHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(SqlqNativeQueryHostApi, sqlq_native_query_host_api, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryHostApi resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_dispose(GObject* object) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(sqlq_native_query_host_api_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryHostApi state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_init(SqlqNativeQueryHostApi* self) {
}

/** Purpose: Bind generated NativeQueryHostApi lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_class_init(SqlqNativeQueryHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_host_api_dispose;
}

static SqlqNativeQueryHostApi* sqlq_native_query_host_api_new(const SqlqNativeQueryHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(g_object_new(sqlq_native_query_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_get_capabilities_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->get_capabilities == nullptr) {
    return;
  }

  g_autoptr(SqlqNativeQueryHostApiGetCapabilitiesResponse) response = self->vtable->get_capabilities(self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "getCapabilities");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "getCapabilities", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_query_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->query == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FlValue* request = value0;
  g_autoptr(SqlqNativeQueryHostApiQueryResponse) response = self->vtable->query(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "query");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "query", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_mutate_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->mutate == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FlValue* request = value0;
  g_autoptr(SqlqNativeQueryHostApiMutateResponse) response = self->vtable->mutate(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "mutate");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "mutate", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_batch_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->batch == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FlValue* request = value0;
  g_autoptr(SqlqNativeQueryHostApiBatchResponse) response = self->vtable->batch(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "batch");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "batch", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_start_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->observe_start == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FlValue* request = value0;
  g_autoptr(SqlqNativeQueryHostApiObserveStartResponse) response = self->vtable->observe_start(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "observeStart");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "observeStart", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_observe_stop_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->observe_stop == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* observer_id = fl_value_get_string(value0);
  g_autoptr(SqlqNativeQueryHostApiObserveStopResponse) response = self->vtable->observe_stop(observer_id, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "observeStop");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "observeStop", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_open_binary_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->open_binary == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FlValue* request = value0;
  g_autoptr(SqlqNativeQueryHostApiOpenBinaryResponse) response = self->vtable->open_binary(request, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "openBinary");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "openBinary", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_close_binary_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->close_binary == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* handle_id = fl_value_get_string(value0);
  g_autoptr(SqlqNativeQueryHostApiCloseBinaryResponse) response = self->vtable->close_binary(handle_id, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "closeBinary");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "closeBinary", error->message);
  }
}

/** Purpose: Decode and dispatch one generated host call. @param channel carries the call. @param message_ contains arguments. @param response_handle receives the reply. @param user_data owns API state. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_host_api_call_extension_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  SqlqNativeQueryHostApi* self = SQLQ_NATIVE_QUERY_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->call_extension == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* namespace_ = fl_value_get_string(value0);
  FlValue* value1 = fl_value_get_list_value(message_, 1);
  const gchar* method = fl_value_get_string(value1);
  FlValue* value2 = fl_value_get_list_value(message_, 2);
  FlValue* args = value2;
  g_autoptr(SqlqNativeQueryHostApiCallExtensionResponse) response = self->vtable->call_extension(namespace_, method, args, self->user_data);
  if (response == nullptr) {
    g_warning("No response returned to %s.%s", "NativeQueryHostApi", "callExtension");
    return;
  }

  g_autoptr(GError) error = NULL;
  if (!fl_basic_message_channel_respond(channel, response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "NativeQueryHostApi", "callExtension", error->message);
  }
}

void sqlq_native_query_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const SqlqNativeQueryHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(SqlqNativeQueryHostApi) api_data = sqlq_native_query_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(SqlqMessageCodec) codec = sqlq_message_codec_new();
  g_autofree gchar* get_capabilities_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.getCapabilities%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_capabilities_channel = fl_basic_message_channel_new(messenger, get_capabilities_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_capabilities_channel, sqlq_native_query_host_api_get_capabilities_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* query_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.query%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) query_channel = fl_basic_message_channel_new(messenger, query_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(query_channel, sqlq_native_query_host_api_query_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* mutate_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.mutate%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) mutate_channel = fl_basic_message_channel_new(messenger, mutate_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(mutate_channel, sqlq_native_query_host_api_mutate_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* batch_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.batch%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) batch_channel = fl_basic_message_channel_new(messenger, batch_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(batch_channel, sqlq_native_query_host_api_batch_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* observe_start_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.observeStart%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) observe_start_channel = fl_basic_message_channel_new(messenger, observe_start_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(observe_start_channel, sqlq_native_query_host_api_observe_start_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* observe_stop_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.observeStop%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) observe_stop_channel = fl_basic_message_channel_new(messenger, observe_stop_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(observe_stop_channel, sqlq_native_query_host_api_observe_stop_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* open_binary_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.openBinary%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) open_binary_channel = fl_basic_message_channel_new(messenger, open_binary_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(open_binary_channel, sqlq_native_query_host_api_open_binary_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* close_binary_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.closeBinary%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) close_binary_channel = fl_basic_message_channel_new(messenger, close_binary_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(close_binary_channel, sqlq_native_query_host_api_close_binary_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* call_extension_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.callExtension%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) call_extension_channel = fl_basic_message_channel_new(messenger, call_extension_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(call_extension_channel, sqlq_native_query_host_api_call_extension_cb, g_object_ref(api_data), g_object_unref);
}

void sqlq_native_query_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(SqlqMessageCodec) codec = sqlq_message_codec_new();
  g_autofree gchar* get_capabilities_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.getCapabilities%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_capabilities_channel = fl_basic_message_channel_new(messenger, get_capabilities_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_capabilities_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* query_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.query%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) query_channel = fl_basic_message_channel_new(messenger, query_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(query_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* mutate_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.mutate%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) mutate_channel = fl_basic_message_channel_new(messenger, mutate_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(mutate_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* batch_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.batch%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) batch_channel = fl_basic_message_channel_new(messenger, batch_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(batch_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* observe_start_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.observeStart%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) observe_start_channel = fl_basic_message_channel_new(messenger, observe_start_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(observe_start_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* observe_stop_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.observeStop%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) observe_stop_channel = fl_basic_message_channel_new(messenger, observe_stop_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(observe_stop_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* open_binary_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.openBinary%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) open_binary_channel = fl_basic_message_channel_new(messenger, open_binary_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(open_binary_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* close_binary_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.closeBinary%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) close_binary_channel = fl_basic_message_channel_new(messenger, close_binary_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(close_binary_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* call_extension_channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryHostApi.callExtension%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) call_extension_channel = fl_basic_message_channel_new(messenger, call_extension_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(call_extension_channel, nullptr, nullptr, nullptr);
}

struct _SqlqNativeQueryFlutterApi {
  GObject parent_instance;

  FlBinaryMessenger* messenger;
  gchar *suffix;
};

G_DEFINE_TYPE(SqlqNativeQueryFlutterApi, sqlq_native_query_flutter_api, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryFlutterApi resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_dispose(GObject* object) {
  SqlqNativeQueryFlutterApi* self = SQLQ_NATIVE_QUERY_FLUTTER_API(object);
  g_clear_object(&self->messenger);
  g_clear_pointer(&self->suffix, g_free);
  G_OBJECT_CLASS(sqlq_native_query_flutter_api_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryFlutterApi state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_init(SqlqNativeQueryFlutterApi* self) {
}

/** Purpose: Bind generated NativeQueryFlutterApi lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_class_init(SqlqNativeQueryFlutterApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_flutter_api_dispose;
}

SqlqNativeQueryFlutterApi* sqlq_native_query_flutter_api_new(FlBinaryMessenger* messenger, const gchar* suffix) {
  SqlqNativeQueryFlutterApi* self = SQLQ_NATIVE_QUERY_FLUTTER_API(g_object_new(sqlq_native_query_flutter_api_get_type(), nullptr));
  self->messenger = FL_BINARY_MESSENGER(g_object_ref(messenger));
  self->suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  return self;
}

struct _SqlqNativeQueryFlutterApiOnObserveEventResponse {
  GObject parent_instance;

  FlValue* error;
};

G_DEFINE_TYPE(SqlqNativeQueryFlutterApiOnObserveEventResponse, sqlq_native_query_flutter_api_on_observe_event_response, G_TYPE_OBJECT)

/** Purpose: Release generated NativeQueryFlutterApiOnObserveEventResponse resources. @param object owns the instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_on_observe_event_response_dispose(GObject* object) {
  SqlqNativeQueryFlutterApiOnObserveEventResponse* self = SQLQ_NATIVE_QUERY_FLUTTER_API_ON_OBSERVE_EVENT_RESPONSE(object);
  g_clear_pointer(&self->error, fl_value_unref);
  G_OBJECT_CLASS(sqlq_native_query_flutter_api_on_observe_event_response_parent_class)->dispose(object);
}

/** Purpose: Initialize generated NativeQueryFlutterApiOnObserveEventResponse state. @param self is the new instance. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_on_observe_event_response_init(SqlqNativeQueryFlutterApiOnObserveEventResponse* self) {
}

/** Purpose: Bind generated NativeQueryFlutterApiOnObserveEventResponse lifecycle methods. @param klass is the generated class. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_on_observe_event_response_class_init(SqlqNativeQueryFlutterApiOnObserveEventResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = sqlq_native_query_flutter_api_on_observe_event_response_dispose;
}

static SqlqNativeQueryFlutterApiOnObserveEventResponse* sqlq_native_query_flutter_api_on_observe_event_response_new(FlValue* response) {
  SqlqNativeQueryFlutterApiOnObserveEventResponse* self = SQLQ_NATIVE_QUERY_FLUTTER_API_ON_OBSERVE_EVENT_RESPONSE(g_object_new(sqlq_native_query_flutter_api_on_observe_event_response_get_type(), nullptr));
  if (fl_value_get_length(response) > 1) {
    self->error = fl_value_ref(response);
  }
  return self;
}

gboolean sqlq_native_query_flutter_api_on_observe_event_response_is_error(SqlqNativeQueryFlutterApiOnObserveEventResponse* self) {
  g_return_val_if_fail(SQLQ_IS_NATIVE_QUERY_FLUTTER_API_ON_OBSERVE_EVENT_RESPONSE(self), FALSE);
  return self->error != nullptr;
}

const gchar* sqlq_native_query_flutter_api_on_observe_event_response_get_error_code(SqlqNativeQueryFlutterApiOnObserveEventResponse* self) {
  g_return_val_if_fail(SQLQ_IS_NATIVE_QUERY_FLUTTER_API_ON_OBSERVE_EVENT_RESPONSE(self), nullptr);
  g_assert(sqlq_native_query_flutter_api_on_observe_event_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 0));
}

const gchar* sqlq_native_query_flutter_api_on_observe_event_response_get_error_message(SqlqNativeQueryFlutterApiOnObserveEventResponse* self) {
  g_return_val_if_fail(SQLQ_IS_NATIVE_QUERY_FLUTTER_API_ON_OBSERVE_EVENT_RESPONSE(self), nullptr);
  g_assert(sqlq_native_query_flutter_api_on_observe_event_response_is_error(self));
  return fl_value_get_string(fl_value_get_list_value(self->error, 1));
}

FlValue* sqlq_native_query_flutter_api_on_observe_event_response_get_error_details(SqlqNativeQueryFlutterApiOnObserveEventResponse* self) {
  g_return_val_if_fail(SQLQ_IS_NATIVE_QUERY_FLUTTER_API_ON_OBSERVE_EVENT_RESPONSE(self), nullptr);
  g_assert(sqlq_native_query_flutter_api_on_observe_event_response_is_error(self));
  return fl_value_get_list_value(self->error, 2);
}

/** Purpose: Finish one generated FlutterApi transport send. @param object is the messenger. @param result is its asynchronous response. @param user_data owns the forwarding task. @returns Nothing. @throws Nothing. */
static void sqlq_native_query_flutter_api_on_observe_event_cb(GObject* object, GAsyncResult* result, gpointer user_data) {
  g_autoptr(GTask) task = G_TASK(user_data);
  if (G_IS_TASK(result)) {
    // Transport finish owns cleanup and preserves explicit cancellation errors.
    // Disable only implicit GTask cancellation so finish always runs.
    g_task_set_check_cancellable(G_TASK(result), FALSE);
  }
  g_autoptr(GError) error = nullptr;
  g_autoptr(GBytes) response_bytes = fl_binary_messenger_send_on_channel_finish(FL_BINARY_MESSENGER(object), result, &error);
  if (response_bytes == nullptr) {
    if (error == nullptr) {
      error = g_error_new(G_IO_ERROR, G_IO_ERROR_FAILED, "Flutter message transport returned no response");
    }
    g_task_return_error(task, g_steal_pointer(&error));
    return;
  }
  g_autoptr(SqlqMessageCodec) codec = sqlq_message_codec_new();
  FlValue* response = fl_message_codec_decode_message(FL_MESSAGE_CODEC(codec), response_bytes, &error);
  if (response == nullptr) {
    if (error == nullptr) {
      error = g_error_new(G_IO_ERROR, G_IO_ERROR_INVALID_DATA, "Flutter message transport returned an invalid response");
    }
    g_task_return_error(task, g_steal_pointer(&error));
    return;
  }
  g_task_return_pointer(task, response, reinterpret_cast<GDestroyNotify>(fl_value_unref));
}

void sqlq_native_query_flutter_api_on_observe_event(SqlqNativeQueryFlutterApi* self, const gchar* observer_id, FlValue* event, GCancellable* cancellable, GAsyncReadyCallback callback, gpointer user_data) {
  g_autoptr(FlValue) args = fl_value_new_list();
  fl_value_append_take(args, fl_value_new_string(observer_id));
  fl_value_append_take(args, fl_value_ref(event));
  g_autofree gchar* channel_name = g_strdup_printf("dev.flutter.pigeon.simple_query_linux.NativeQueryFlutterApi.onObserveEvent%s", self->suffix);
  g_autoptr(SqlqMessageCodec) codec = sqlq_message_codec_new();
  g_autoptr(GError) error = nullptr;
  g_autoptr(GBytes) message = fl_message_codec_encode_message(FL_MESSAGE_CODEC(codec), args, &error);
  g_autoptr(GTask) task = g_task_new(self, cancellable, callback, user_data);
  // Forward explicit transport outcomes instead of bypassing transport finish.
  g_task_set_check_cancellable(task, FALSE);
  if (message == nullptr) {
    if (error == nullptr) {
      error = g_error_new(G_IO_ERROR, G_IO_ERROR_INVALID_DATA, "Failed to encode Flutter message");
    }
    g_task_return_error(task, g_steal_pointer(&error));
    return;
  }
  fl_binary_messenger_send_on_channel(self->messenger, channel_name, message, cancellable, sqlq_native_query_flutter_api_on_observe_event_cb, g_steal_pointer(&task));
}

SqlqNativeQueryFlutterApiOnObserveEventResponse* sqlq_native_query_flutter_api_on_observe_event_finish(SqlqNativeQueryFlutterApi* self, GAsyncResult* result, GError** error) {
  GTask* task = G_TASK(result);
  g_autoptr(FlValue) response = static_cast<FlValue*>(g_task_propagate_pointer(task, error));
  if (response == nullptr) {
    return nullptr;
  }
  return sqlq_native_query_flutter_api_on_observe_event_response_new(response);
}
