name: simple_query_example
description: Example app for simple_query federated plugin.
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  simple_query:
    path: ../packages/simple_query

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
