// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.simplezen.simple_query

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is QueryFlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): QueryFlutterError {
  return QueryFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class QueryFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Type of content change observed by ContentObserver. */
enum class ContentChangeType(val raw: Int) {
  INSERT(0),
  UPDATE(1),
  DELETE(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): ContentChangeType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Type of batch operation in applyBatch. */
enum class BatchOperationType(val raw: Int) {
  INSERT(0),
  UPDATE(1),
  DELETE(2),
  ASSERT_QUERY(3);

  companion object {
    fun ofRaw(raw: Int): BatchOperationType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Request for a query operation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class QueryRequest (
  /** Content URI to query (e.g., "content://sms", "content://contacts/data"). */
  val contentUri: String,
  /** Columns to return. Null returns all columns. */
  val projection: List<String?>? = null,
  /** SQL WHERE clause (without "WHERE"). Use ? for parameters. */
  val selection: String? = null,
  /** Values to substitute for ? placeholders in selection. */
  val selectionArgs: List<String?>? = null,
  /** SQL ORDER BY clause (without "ORDER BY"). */
  val sortOrder: String? = null,
  /** Maximum number of rows to return. */
  val limit: Long? = null,
  /** Number of rows to skip (for pagination). */
  val offset: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueryRequest {
      val contentUri = pigeonVar_list[0] as String
      val projection = pigeonVar_list[1] as List<String?>?
      val selection = pigeonVar_list[2] as String?
      val selectionArgs = pigeonVar_list[3] as List<String?>?
      val sortOrder = pigeonVar_list[4] as String?
      val limit = pigeonVar_list[5] as Long?
      val offset = pigeonVar_list[6] as Long?
      return QueryRequest(contentUri, projection, selection, selectionArgs, sortOrder, limit, offset)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
      projection,
      selection,
      selectionArgs,
      sortOrder,
      limit,
      offset,
    )
  }
}

/**
 * Response from a query operation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class QueryResponse (
  /**
   * List of rows, each row is a map of column name to value.
   * BLOB columns return null; use openStream() to retrieve binary data.
   * Note: Uses Object? to avoid Pigeon CastList issues with nested generics.
   * Each row is actually `Map<Object?, Object?>` - convert with `.cast<String?, Object?>()`.
   */
  val rows: List<Any?>,
  /** Total number of rows returned. */
  val rowCount: Long,
  /** Column names in result set. */
  val columnNames: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): QueryResponse {
      val rows = pigeonVar_list[0] as List<Any?>
      val rowCount = pigeonVar_list[1] as Long
      val columnNames = pigeonVar_list[2] as List<String?>?
      return QueryResponse(rows, rowCount, columnNames)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rows,
      rowCount,
      columnNames,
    )
  }
}

/**
 * Request to insert a row.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class InsertRequest (
  val contentUri: String,
  /** Column name to value map. */
  val values: Map<String?, Any?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InsertRequest {
      val contentUri = pigeonVar_list[0] as String
      val values = pigeonVar_list[1] as Map<String?, Any?>
      return InsertRequest(contentUri, values)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
      values,
    )
  }
}

/**
 * Request to insert multiple rows.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BulkInsertRequest (
  val contentUri: String,
  /** List of rows to insert. */
  val valuesList: List<Map<String?, Any?>?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BulkInsertRequest {
      val contentUri = pigeonVar_list[0] as String
      val valuesList = pigeonVar_list[1] as List<Map<String?, Any?>?>
      return BulkInsertRequest(contentUri, valuesList)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
      valuesList,
    )
  }
}

/**
 * Request to update rows.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class UpdateRequest (
  val contentUri: String,
  /** Column name to new value map. */
  val values: Map<String?, Any?>,
  /** SQL WHERE clause. */
  val selection: String? = null,
  /** Values for ? placeholders. */
  val selectionArgs: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UpdateRequest {
      val contentUri = pigeonVar_list[0] as String
      val values = pigeonVar_list[1] as Map<String?, Any?>
      val selection = pigeonVar_list[2] as String?
      val selectionArgs = pigeonVar_list[3] as List<String?>?
      return UpdateRequest(contentUri, values, selection, selectionArgs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
      values,
      selection,
      selectionArgs,
    )
  }
}

/**
 * Request to delete rows.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DeleteRequest (
  val contentUri: String,
  /** SQL WHERE clause. */
  val selection: String? = null,
  /** Values for ? placeholders. */
  val selectionArgs: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DeleteRequest {
      val contentUri = pigeonVar_list[0] as String
      val selection = pigeonVar_list[1] as String?
      val selectionArgs = pigeonVar_list[2] as List<String?>?
      return DeleteRequest(contentUri, selection, selectionArgs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
      selection,
      selectionArgs,
    )
  }
}

/**
 * Single operation in a batch.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatchOperation (
  val type: BatchOperationType,
  val contentUri: String,
  /** Values for insert/update. */
  val values: Map<String?, Any?>? = null,
  /** Selection for update/delete/assert. */
  val selection: String? = null,
  val selectionArgs: List<String?>? = null,
  /** For assertQuery: expected row count. */
  val expectedCount: Long? = null,
  /** Index of prior operation to reference for value. */
  val backReferenceIndex: Long? = null,
  /** Column to use from back-referenced result. */
  val backReferenceColumn: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatchOperation {
      val type = pigeonVar_list[0] as BatchOperationType
      val contentUri = pigeonVar_list[1] as String
      val values = pigeonVar_list[2] as Map<String?, Any?>?
      val selection = pigeonVar_list[3] as String?
      val selectionArgs = pigeonVar_list[4] as List<String?>?
      val expectedCount = pigeonVar_list[5] as Long?
      val backReferenceIndex = pigeonVar_list[6] as Long?
      val backReferenceColumn = pigeonVar_list[7] as String?
      return BatchOperation(type, contentUri, values, selection, selectionArgs, expectedCount, backReferenceIndex, backReferenceColumn)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      contentUri,
      values,
      selection,
      selectionArgs,
      expectedCount,
      backReferenceIndex,
      backReferenceColumn,
    )
  }
}

/**
 * Request for batch operations.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatchRequest (
  /** ContentProvider authority (e.g., "sms", "com.android.contacts"). */
  val authority: String,
  /** List of operations to apply atomically. */
  val operations: List<BatchOperation?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatchRequest {
      val authority = pigeonVar_list[0] as String
      val operations = pigeonVar_list[1] as List<BatchOperation?>
      return BatchRequest(authority, operations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      authority,
      operations,
    )
  }
}

/**
 * Result of a single batch operation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BatchOperationResult (
  /** URI of inserted row (for insert operations). */
  val uri: String? = null,
  /** Number of affected rows (for update/delete). */
  val count: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BatchOperationResult {
      val uri = pigeonVar_list[0] as String?
      val count = pigeonVar_list[1] as Long?
      return BatchOperationResult(uri, count)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      count,
    )
  }
}

/**
 * Specification for a joined/related query.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JoinSpec (
  /** Key name for this join in the result. */
  val name: String,
  /** Content URI for the related table. */
  val contentUri: String,
  /** Column in child table that references parent. */
  val foreignKeyColumn: String,
  /** Column in parent table (usually "_id"). */
  val parentKeyColumn: String,
  /** Columns to return from child table. */
  val projection: List<String?>? = null,
  /** Additional filter for child rows. */
  val selection: String? = null,
  val selectionArgs: List<String?>? = null,
  val sortOrder: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JoinSpec {
      val name = pigeonVar_list[0] as String
      val contentUri = pigeonVar_list[1] as String
      val foreignKeyColumn = pigeonVar_list[2] as String
      val parentKeyColumn = pigeonVar_list[3] as String
      val projection = pigeonVar_list[4] as List<String?>?
      val selection = pigeonVar_list[5] as String?
      val selectionArgs = pigeonVar_list[6] as List<String?>?
      val sortOrder = pigeonVar_list[7] as String?
      return JoinSpec(name, contentUri, foreignKeyColumn, parentKeyColumn, projection, selection, selectionArgs, sortOrder)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      contentUri,
      foreignKeyColumn,
      parentKeyColumn,
      projection,
      selection,
      selectionArgs,
      sortOrder,
    )
  }
}

/**
 * Request for a query with joins.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JoinQueryRequest (
  /** The primary/parent query. */
  val primary: QueryRequest,
  /** Related queries to join. */
  val joins: List<JoinSpec?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JoinQueryRequest {
      val primary = pigeonVar_list[0] as QueryRequest
      val joins = pigeonVar_list[1] as List<JoinSpec?>
      return JoinQueryRequest(primary, joins)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      primary,
      joins,
    )
  }
}

/**
 * A row with nested related data.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JoinedRow (
  /**
   * Primary row data.
   * Note: Actually `Map<Object?, Object?>` - convert keys with `.cast<String?, Object?>()`.
   */
  val data: Any,
  /**
   * Related rows keyed by JoinSpec.name.
   * Note: Uses Object to avoid Pigeon CastList issues with nested generics.
   */
  val related: Any
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JoinedRow {
      val data = pigeonVar_list[0] as Any
      val related = pigeonVar_list[1] as Any
      return JoinedRow(data, related)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
      related,
    )
  }
}

/**
 * Response for a join query.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class JoinQueryResponse (
  val rows: List<JoinedRow?>,
  val rowCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JoinQueryResponse {
      val rows = pigeonVar_list[0] as List<JoinedRow?>
      val rowCount = pigeonVar_list[1] as Long
      return JoinQueryResponse(rows, rowCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rows,
      rowCount,
    )
  }
}

/**
 * Descriptor for an open stream.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StreamDescriptor (
  /** Unique ID for this stream (for closing). */
  val streamId: String,
  /** Path to the read end of the named pipe. */
  val pipePath: String,
  /** MIME type of the content. */
  val mimeType: String? = null,
  /** Size in bytes if known. */
  val size: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamDescriptor {
      val streamId = pigeonVar_list[0] as String
      val pipePath = pigeonVar_list[1] as String
      val mimeType = pigeonVar_list[2] as String?
      val size = pigeonVar_list[3] as Long?
      return StreamDescriptor(streamId, pipePath, mimeType, size)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      streamId,
      pipePath,
      mimeType,
      size,
    )
  }
}

/**
 * Error during streaming.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StreamError (
  val streamId: String,
  val contentUri: String,
  val message: String,
  val bytesTransferred: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamError {
      val streamId = pigeonVar_list[0] as String
      val contentUri = pigeonVar_list[1] as String
      val message = pigeonVar_list[2] as String
      val bytesTransferred = pigeonVar_list[3] as Long?
      return StreamError(streamId, contentUri, message, bytesTransferred)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      streamId,
      contentUri,
      message,
      bytesTransferred,
    )
  }
}

/**
 * Event from ContentObserver.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ContentChangeEvent (
  /** ID of the observer that fired. */
  val observerId: String,
  /** URI that changed. */
  val uri: String,
  /** Type of change. */
  val changeType: ContentChangeType,
  /** Additional flags from the observer. */
  val flags: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ContentChangeEvent {
      val observerId = pigeonVar_list[0] as String
      val uri = pigeonVar_list[1] as String
      val changeType = pigeonVar_list[2] as ContentChangeType
      val flags = pigeonVar_list[3] as Long?
      return ContentChangeEvent(observerId, uri, changeType, flags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      observerId,
      uri,
      changeType,
      flags,
    )
  }
}

/**
 * Request to register an observer.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ObserverRequest (
  val contentUri: String,
  /** If true, also notify for changes to descendant URIs. */
  val notifyForDescendants: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ObserverRequest {
      val contentUri = pigeonVar_list[0] as String
      val notifyForDescendants = pigeonVar_list[1] as Boolean
      return ObserverRequest(contentUri, notifyForDescendants)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
      notifyForDescendants,
    )
  }
}

/**
 * Response for getType().
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TypeResponse (
  /** MIME type (e.g., "vnd.android.cursor.dir/sms"). */
  val mimeType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TypeResponse {
      val mimeType = pigeonVar_list[0] as String?
      return TypeResponse(mimeType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      mimeType,
    )
  }
}

/**
 * Request for provider call().
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProviderCallRequest (
  val authority: String,
  val method: String,
  val arg: String? = null,
  val extras: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProviderCallRequest {
      val authority = pigeonVar_list[0] as String
      val method = pigeonVar_list[1] as String
      val arg = pigeonVar_list[2] as String?
      val extras = pigeonVar_list[3] as Map<String?, Any?>?
      return ProviderCallRequest(authority, method, arg, extras)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      authority,
      method,
      arg,
      extras,
    )
  }
}

/**
 * Response from provider call().
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProviderCallResponse (
  val result: Map<String?, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProviderCallResponse {
      val result = pigeonVar_list[0] as Map<String?, Any?>?
      return ProviderCallResponse(result)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      result,
    )
  }
}
private open class QueryPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ContentChangeType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BatchOperationType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueryRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          QueryResponse.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InsertRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BulkInsertRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UpdateRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DeleteRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatchOperation.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatchRequest.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BatchOperationResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JoinSpec.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JoinQueryRequest.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JoinedRow.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JoinQueryResponse.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamDescriptor.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamError.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ContentChangeEvent.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ObserverRequest.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TypeResponse.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProviderCallRequest.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProviderCallResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ContentChangeType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is BatchOperationType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is QueryRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is QueryResponse -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is InsertRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BulkInsertRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is UpdateRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is DeleteRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BatchOperation -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is BatchRequest -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is BatchOperationResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is JoinSpec -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is JoinQueryRequest -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is JoinedRow -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is JoinQueryResponse -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is StreamDescriptor -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is StreamError -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is ContentChangeEvent -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is ObserverRequest -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is TypeResponse -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is ProviderCallRequest -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is ProviderCallResponse -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface QueryHostApi {
  fun query(request: QueryRequest, callback: (Result<QueryResponse>) -> Unit)
  fun queryWithJoins(request: JoinQueryRequest, callback: (Result<JoinQueryResponse>) -> Unit)
  /** Insert a row. Returns URI of inserted row. */
  fun insert(request: InsertRequest, callback: (Result<String?>) -> Unit)
  /** Insert multiple rows. Returns count of inserted rows. */
  fun bulkInsert(request: BulkInsertRequest, callback: (Result<Long>) -> Unit)
  /** Update rows. Returns count of updated rows. */
  fun update(request: UpdateRequest, callback: (Result<Long>) -> Unit)
  /** Delete rows. Returns count of deleted rows. */
  fun delete(request: DeleteRequest, callback: (Result<Long>) -> Unit)
  /** Apply batch operations atomically. */
  fun applyBatch(request: BatchRequest, callback: (Result<List<BatchOperationResult?>>) -> Unit)
  /**
   * Open a stream for reading binary content.
   * Returns StreamDescriptor with pipe path for zero-copy reading.
   */
  fun openStream(contentUri: String, callback: (Result<StreamDescriptor>) -> Unit)
  /**
   * Extract content to a temp file.
   * Returns file:// URI to the temp file.
   */
  fun extractToFile(contentUri: String, callback: (Result<String?>) -> Unit)
  /** Close an open stream and release resources. */
  fun closeStream(streamId: String, callback: (Result<Unit>) -> Unit)
  /** Register a ContentObserver. Returns observer ID. */
  fun registerObserver(request: ObserverRequest, callback: (Result<String>) -> Unit)
  /** Unregister a ContentObserver. */
  fun unregisterObserver(observerId: String, callback: (Result<Unit>) -> Unit)
  /** Unregister all observers. */
  fun unregisterAllObservers(callback: (Result<Unit>) -> Unit)
  /** Get MIME type for a content URI. */
  fun getType(contentUri: String, callback: (Result<TypeResponse>) -> Unit)
  /** Canonicalize a URI for cross-device portability. */
  fun canonicalize(contentUri: String, callback: (Result<String?>) -> Unit)
  /** Reverse canonicalization. */
  fun uncanonicalize(contentUri: String, callback: (Result<String?>) -> Unit)
  /** Call a provider-defined method. */
  fun call(request: ProviderCallRequest, callback: (Result<ProviderCallResponse>) -> Unit)
  /**
   * Returns true if the calling app holds [permissionName]
   * (a fully-qualified Android permission identifier such as
   * `android.permission.READ_CONTACTS`). Implemented via
   * `Context.checkSelfPermission`. Synchronous on the native side; pigeon
   * makes it async on the Dart side.
   */
  fun hasPermission(permissionName: String, callback: (Result<Boolean>) -> Unit)
  /**
   * Returns the device's `Build.VERSION.SDK_INT`. Used by the Dart-side
   * permission catalog to pick between legacy and modern media permissions
   * (`READ_EXTERNAL_STORAGE` vs `READ_MEDIA_*`).
   */
  fun getAndroidSdkInt(callback: (Result<Long>) -> Unit)

  companion object {
    /** The codec used by QueryHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      QueryPigeonCodec()
    }
    /** Sets up an instance of `QueryHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: QueryHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.query$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as QueryRequest
            api.query(requestArg) { result: Result<QueryResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.queryWithJoins$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as JoinQueryRequest
            api.queryWithJoins(requestArg) { result: Result<JoinQueryResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.insert$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as InsertRequest
            api.insert(requestArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.bulkInsert$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BulkInsertRequest
            api.bulkInsert(requestArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.update$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as UpdateRequest
            api.update(requestArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.delete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DeleteRequest
            api.delete(requestArg) { result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.applyBatch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BatchRequest
            api.applyBatch(requestArg) { result: Result<List<BatchOperationResult?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.openStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentUriArg = args[0] as String
            api.openStream(contentUriArg) { result: Result<StreamDescriptor> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.extractToFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentUriArg = args[0] as String
            api.extractToFile(contentUriArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.closeStream$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val streamIdArg = args[0] as String
            api.closeStream(streamIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.registerObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ObserverRequest
            api.registerObserver(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.unregisterObserver$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val observerIdArg = args[0] as String
            api.unregisterObserver(observerIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.unregisterAllObservers$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.unregisterAllObservers{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.getType$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentUriArg = args[0] as String
            api.getType(contentUriArg) { result: Result<TypeResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.canonicalize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentUriArg = args[0] as String
            api.canonicalize(contentUriArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.uncanonicalize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentUriArg = args[0] as String
            api.uncanonicalize(contentUriArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.call$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ProviderCallRequest
            api.call(requestArg) { result: Result<ProviderCallResponse> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.hasPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionNameArg = args[0] as String
            api.hasPermission(permissionNameArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.simple_query.QueryHostApi.getAndroidSdkInt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAndroidSdkInt{ result: Result<Long> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class QueryFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by QueryFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      QueryPigeonCodec()
    }
  }
  /** Called when observed content changes. */
  fun onContentChange(eventArg: ContentChangeEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.simple_query.QueryFlutterApi.onContentChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(QueryFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  /** Called when a stream encounters an error. */
  fun onStreamError(errorArg: StreamError, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.simple_query.QueryFlutterApi.onStreamError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(QueryFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
