name: simple_query_android
description: Android implementation for the simple_query federated plugin.
version: 0.6.0
homepage: https://github.com/simplezen/simple-query
repository: https://github.com/simplezen/simple-query
issue_tracker: https://github.com/simplezen/simple-query/issues

topics:
  - flutter
  - plugin
  - contacts
  - query
  - files

environment:
  sdk: ^3.6.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  simple_query_platform_interface:
    path: ../simple_query_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: 22.7.4

flutter:
  plugin:
    implements: simple_query
    platforms:
      android:
        package: io.simplezen.simple_query
        pluginClass: SimpleQueryPlugin
        dartPluginClass: SimpleQueryAndroid
