// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class NativeQueryPigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "NativeQueryPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeQueryPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> NativeQueryPigeonError {
  return NativeQueryPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class NativeQueryPigeonCodecReader: FlutterStandardReader {
}

private class NativeQueryPigeonCodecWriter: FlutterStandardWriter {
}

private class NativeQueryPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeQueryPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeQueryPigeonCodecWriter(data: data)
  }
}

class NativeQueryPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeQueryPigeonCodec(readerWriter: NativeQueryPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeQueryHostApi {
  func getCapabilities() throws -> [String?: Any?]
  func query(request: [String?: Any?]) throws -> [String?: Any?]
  func mutate(request: [String?: Any?]) throws -> [String?: Any?]
  func batch(request: [String?: Any?]) throws -> [String?: Any?]
  func observeStart(request: [String?: Any?]) throws -> String
  func observeStop(observerId: String) throws
  func openBinary(request: [String?: Any?]) throws -> [String?: Any?]
  func closeBinary(handleId: String) throws
  func callExtension(namespace: String, method: String, args: [String?: Any?]?) throws -> [String?: Any?]?
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeQueryHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeQueryPigeonCodec.shared }
  /// Sets up an instance of `NativeQueryHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeQueryHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCapabilities()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let queryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.query\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      queryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! [String?: Any?]
        do {
          let result = try api.query(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      queryChannel.setMessageHandler(nil)
    }
    let mutateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.mutate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      mutateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! [String?: Any?]
        do {
          let result = try api.mutate(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      mutateChannel.setMessageHandler(nil)
    }
    let batchChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.batch\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      batchChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! [String?: Any?]
        do {
          let result = try api.batch(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      batchChannel.setMessageHandler(nil)
    }
    let observeStartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.observeStart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      observeStartChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! [String?: Any?]
        do {
          let result = try api.observeStart(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      observeStartChannel.setMessageHandler(nil)
    }
    let observeStopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.observeStop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      observeStopChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let observerIdArg = args[0] as! String
        do {
          try api.observeStop(observerId: observerIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      observeStopChannel.setMessageHandler(nil)
    }
    let openBinaryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.openBinary\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openBinaryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! [String?: Any?]
        do {
          let result = try api.openBinary(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openBinaryChannel.setMessageHandler(nil)
    }
    let closeBinaryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.closeBinary\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeBinaryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleIdArg = args[0] as! String
        do {
          try api.closeBinary(handleId: handleIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeBinaryChannel.setMessageHandler(nil)
    }
    let callExtensionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.simple_query_macos.NativeQueryHostApi.callExtension\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      callExtensionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let namespaceArg = args[0] as! String
        let methodArg = args[1] as! String
        let argsArg: [String?: Any?]? = nilOrValue(args[2])
        do {
          let result = try api.callExtension(namespace: namespaceArg, method: methodArg, args: argsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      callExtensionChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol NativeQueryFlutterApiProtocol {
  func onObserveEvent(observerId observerIdArg: String, event eventArg: [String?: Any?], completion: @escaping (Result<Void, NativeQueryPigeonError>) -> Void)
}
class NativeQueryFlutterApi: NativeQueryFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: NativeQueryPigeonCodec {
    return NativeQueryPigeonCodec.shared
  }
  func onObserveEvent(observerId observerIdArg: String, event eventArg: [String?: Any?], completion: @escaping (Result<Void, NativeQueryPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.simple_query_macos.NativeQueryFlutterApi.onObserveEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([observerIdArg, eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(NativeQueryPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
